FROM m.docker-registry.ir/python:3.9-slim

RUN apt-get update -y

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY src /app

EXPOSE 5000
ENV FLASK_APP='privatenote'
ENV FLASK_ENV='development'

CMD ["flask", "run", "--host=0.0.0.0"]