apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: rajabpouramir/mygoapp:2
        name: myapp
        resources: {}
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: config.json
            subPath: production-config.json
            name: config-map
      volumes:
        - name: config-map
          configMap:
            name: myapp
status: {}
