apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: rajabpouramir/pv-note:latest
          name: myapp
          resources: {}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myapp-configmap
