apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: mongodb-stateful-service
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        replicaset: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
      containers:
        - name: mongodb
          image: docker.repos.balad.ir/mongo:4.0.4
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
            - configMapRef:
                name: mongodb-configmap
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi