apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: privatenote
  name: privatenote-deployment
spec:
  replicas: {{ .Values.app.replicasCount }}
  selector:
    matchLabels:
      app: privatenote
  strategy: {}
  template:
    metadata:
      labels:
        app: privatenote
    spec:
      containers:
        - image: {{ .Values.app.image }}
          name: private-note-container
          resources: {}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mongodb-configmap
            - secretRef:
                name: mongodb-secret
