apiVersion: v1
kind: Service
metadata:
  name: privatenote-service
spec:
  selector:
    app: privatenote
  ports:
    - protocol: TCP
      port: {{ .Values.appService.Port }}
      targetPort: 5000
