apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-privatenote-service
spec:
  selector:
    app: {{ .Release.Name }}-privatenote
  ports:
    - protocol: TCP
      port: {{ .Values.appService.Port }}
      targetPort: 5000
