apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  replicas: {{ .Values.db.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.db.image }}
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
            - configMapRef:
                name: mongodb-configmap
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: {{ .Release.Name }}-mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongodb-pvc
