apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-privatenote-deployment
  labels:
    app: privatenote
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.privatenoteDeployment.replicas }}
  selector:
    matchLabels:
      app: privatenote
    {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: privatenote
      {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: mongodb-configmap
        - secretRef:
            name: mongodb-secret
        image: {{ .Values.privatenoteDeployment.privateNoteContainer.image.repository }}:{{
          .Values.privatenoteDeployment.privateNoteContainer.image.tag | default .Chart.AppVersion
          }}
        name: private-note-container
        ports:
        - containerPort: 5000
        resources: {}