apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  MONGO_INITDB_ROOT_PASSWORD: {{ mongodbSecret.mongoInitdbRootPassword }}
  MONGO_INITDB_ROOT_USERNAME: {{ mongodbSecret.mongoInitdbRootUsername }}