apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodbSecret.mongoInitdbRootPassword }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodbSecret.mongoInitdbRootUsername }}